package pot

const (
	// EXPIRATION_NOT_SET 未设置过期时间
	EXPIRATION_NOT_SET = -1

	// EXPIRATION_IS_EXPIRED key不存在||已过期
	EXPIRATION_IS_EXPIRED = -2
)

const (
	// POT_ACTION_RESULT_EXISTS 操作有数据/成功
	POT_ACTION_RESULT_EXISTS = 1
)
